version: 0.0.1

# Google Cloud SQL database
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: cloud peacock tables
  url: jdbc:mysql://google/AppData?cloudSqlInstance=peacock-productivity-suite:us-west1:peacock-productivity-api&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.globally_quoted_identifiers: true

server:
  rootPath: '/api/*'
  applicationContextPath: /
  applicationConnectors:
  - type: http
    port: 8280
  adminConnectors:
  - type: http
    port: 8281

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    org.google.cloud: INFO
    org.hibernate.SQL:
      level: DEBUG
  appenders:
  - type: console
  - type: file
    # The file to which current statements will be logged.
    currentLogFilename: ./logs/server.log

    # When the log file rotates, the archived log will be renamed to this and gzipped. The
    # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
    # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
    archivedLogFilenamePattern: ./logs/server-%d.log.gz

    # The number of archived files to keep.
    archivedFileCount: 5

    # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
    timeZone: UTC
